priorityClassName support
rancher/backup-restore-operator pull request #103
Opened 2021-05-05 16:59 UTC by jasonhancock

Adds the ability to specify a priority class name.

2021-05-25 19:43 UTC, jiaqiluo commented
@jasonhancock  Can you elaborate on the use case of the  `priorityClassName` filed here?

2021-05-25 19:57 UTC, jasonhancock commented
@jiaqiluo we make use of [priority classes](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/) in our k8s clusters to help facilitate workloads to be scheduled on our clusters and preempt other workloads. We'd like the ability to set a priority class on the pods.

2021-05-25 22:00 UTC, jiaqiluo requested changes

2021-05-25 22:19 UTC, jasonhancock commented on charts/rancher-backup/templates/deployment.yaml
> +      {{- if ne .Values.priorityClassName "" }}
updated per suggestion

2021-05-25 23:03 UTC, jiaqiluo approved these changes
LGTM.

2021-05-26 16:27 UTC, ryansann approved these changes

2021-05-27 19:37 UTC, merged

2021-05-27 19:40 UTC, jiaqiluo commented
@jasonhancock Thank you for you contribution to the project!