[Backport][v2.7] GHA CI
rancher/backup-restore-operator pull request #472
Opened 2024-05-13 15:49 UTC by alexandreLamarre

Backport of :
https://github.com/rancher/backup-restore-operator/pull/455
https://github.com/rancher/backup-restore-operator/pull/457
https://github.com/rancher/backup-restore-operator/pull/469

2024-05-13 15:50 UTC, alexandreLamarre commented on .github/workflows/publish.yaml
> +    uses: rancher/backup-restore-operator/.github/workflows/ci.yaml@release/v5.0
Same comment as the 2.8 backport
> Decided to leave this as reference to the current default branch, but open to changing it to reference the target branch release/v4.0 -- applies to a couple of other places.
> 
> Applies to a couple of other places. Perhaps discussing/documenting backport standards for CI is a good idea to be addressed in a follow up PR?

2024-06-17 17:32 UTC, ericpromislow commented on .github/workflows/ci.yaml
> +      - release/v5.0
Shouldn't this just be `release/v*` so we don't have to keep updating it?

2024-06-17 17:33 UTC, ericpromislow commented on .github/workflows/ci.yaml
> +        os : [
extra white-space at the end

2024-06-17 17:33 UTC, ericpromislow commented on .github/workflows/ci.yaml
> +      matrix:
Alternative to run on both platforms:
```
 strategy:
      matrix:
        archBox:
        - { arch: amd64, vmArch: x64 }
        - { arch: arm64, vmArch: arm64 }
    runs-on: runs-on,runner=1cpu-linux-${{ matrix.archBox.vmArch }},run-id=${{ github.run_id }}
    ```

2024-06-17 17:34 UTC, ericpromislow commented on .github/workflows/ci.yaml
> +      - name : Debug
I use this too, but I assume we want to pull out the Debug parts once everything's working

2024-06-17 17:35 UTC, ericpromislow commented on .github/workflows/publish.yaml
> +        uses: docker/setup-buildx-action@v3
Extra white-space at end of line 37

2024-06-17 17:49 UTC, ericpromislow commented on .github/workflows/scripts/setup-cluster.sh
> +k3d cluster create $CLUSTER_NAME --image "docker.io/rancher/k3s:${K3S_VERSION}"
The `docker.io/` part isn't needed

2024-06-17 17:51 UTC, ericpromislow commented on .github/workflows/scripts/setup-cluster.sh
> +
Space on line 30 not needed (`git diff` is complaining about these)

2024-06-17 17:52 UTC, ericpromislow commented on package/Dockerfile
> +COPY --from=builder /usr/src/app/bin/backup-restore-operator  /usr/bin/
extra space after `backup-restore-operator`

2024-06-17 17:53 UTC, ericpromislow commented on scripts/integration
> +source ./scripts/version
I thought leaving it as `$(dirname $0)` would be better in case you're running this from some other directory

2024-06-17 18:10 UTC, ericpromislow commented on scripts/integration
> +    echo "$(date --utc +%Y-%m-%dT%H:%M:%SZ) $*"
The `--utc` option isn't recognized on Darwin (`/bin/date` so I'm not running some variant) but `-u` is a shortcut for it on linux. So better to just go with `-u`

2024-06-17 18:36 UTC, ericpromislow requested changes
Just white-space issues, although you might want to try the dual-runner solution and see if CI succeeds on both platforms.

2024-07-19 00:57 UTC, mallardduck commented
I think that technically for both of these backports, we don't even need to bring the `.github` folder over. GHA always finds workflows based on the current default branch. And we're not likely to ever "rollback" and use an older branch as default, so they'll just be unused blobs of data on old branches.

As we move forward the new base branch (eventually `release/v6.0`) will inherit the same workflows we have when we branch. And for example, if we need different release processes for 6.0 while still using "old" workflows for old branches we would maintain both workflows in parallel and differ based on branches/tags that trigger them.

What is probably worth backporting though are mainly the parts that remove drone and bring the new build scripts. Since I think only scripts we put under `.github` will be in the context of the running action by default. And other scripts (like `./scripts` folder) are accessed via what the GHA clones.

2024-07-26 15:00 UTC, mallardduck approved these changes

2024-07-26 15:00 UTC, merged