goreleaser is failing with error 422 - this might fix it.
rancher/backup-restore-operator pull request #488
Opened 2024-07-17 22:23 UTC by ericpromislow

2024-07-17 22:24 UTC, alexandreLamarre approved these changes

2024-07-17 22:26 UTC, mallardduck commented
I don't think this will hurt, but it also seems like the fails are because it's trying to upload to the RC still. Since I'd you look at the RC release it has non-rc artifacts

2024-07-17 22:37 UTC, mallardduck requested changes
I think instead of this we need to set `GORELEASER_CURRENT_TAG` to the tag we're building - that way when we have situations like right now where two tags point to the same SHA it won't get confused.

2024-07-18 13:13 UTC, mallardduck commented
Gonna close this for now since I think we solved it in #489

2024-07-18 13:13 UTC, closed without merging